name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行一次，可以根据需要调整

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/master 

      - name: Push changes back to fork
        run: git push origin master 
